services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: smart-favorites-db
    restart: 'always'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${SERVICE_DB_NAME}
    ports:
      - "${SERVICE_DB_PORT}:5432"
    volumes:
      - smart-favorites-db-data:/var/lib/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  smart-favorites-db-data: